# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html

stages:
    - build
    - deploy

build-job:
    stage: build
    image: docker:latest
    # services:
    #     - docker:dind
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - echo "Compiling the code..."

        - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/frontend:latest .
        - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
        - docker push $CI_REGISTRY_IMAGE/frontend:latest

        - echo "Compile complete."

deploy-job:
    stage: deploy
    image: docker:latest
    environment: production
    when: manual
    script:
        - echo "Deploying application..."

        - ssh -o StrictHostKeyChecking=no -i <path-to-private_key> root@<your-vps-ip> "cd ./menuriom && docker-compose pull && docker-compose up -d"

        - echo "Application successfully deployed."
